name: 'Firebase Distribution Upload'
description: 'Uploads a file (apk, aab or ipa) to Firebase Distribution'
author: 'Alessandro Basso'
inputs: 
  appId:
    description: 'App id can be found on the General Settings page'
    required: true
  token:
    description: 'Upload token - see Firebase CLI Reference'
    required: true
  file:
    description: 'File to upload (.apk or .ipa)'
    required: true
  groups:
    description: 'Distribution groups'
    required: false
  releaseNotes:
    description: 'Release notes visible on release page'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Upload to Firebase Distribution
      run: |
        export FIREBASE_TOKEN="${{ inputs.token }}"
        firebase \
          appdistribution:distribute \
          "${{ inputs.file }}" \
          --app "${{ inputs.appId }}" \
          --groups "${{ inputs.groups }}" \
          --release-notes "${{ inputs.releaseNotes }}" |
        {
          while read -r line; do
            echo $line
            if [[ $line == *"View this release in the Firebase console"* ]]; then
              CONSOLE_URI=$(echo "$line" | sed -e 's/.*: //' -e 's/^ *//;s/ *$//')
              echo "FIREBASE_CONSOLE_URI=$CONSOLE_URI" >>"$GITHUB_OUTPUT"
            elif [[ $line == *"Share this release with testers who have access"* ]]; then
              TESTING_URI=$(echo "$line" | sed -e 's/.*: //' -e 's/^ *//;s/ *$//')
              echo "TESTING_URI=$TESTING_URI" >>"$GITHUB_OUTPUT"
            elif [[ $line == *"Download the release binary"* ]]; then
              BINARY_URI=$(echo "$line" | sed -e 's/.*: //' -e 's/^ *//;s/ *$//')
              echo "BINARY_DOWNLOAD_URI=$BINARY_URI" >>"$GITHUB_OUTPUT"
            fi
          done
        }
      shell: bash
        
